language: python
sudo: false
python:
  - "2.7"
  - "3.3"
install:
  - pip install codecov coverage catkin_pkg rosdep
script:
- nosetests --verbose --with-coverage --cover-erase --cover-package=catkin_lint test
after_success:
  - codecov

